name: Terraform E-commerce Apply

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    environment: ecommerce
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TERRAFORM_VERSION: "0.12.15"
    steps:
      - uses: actions/checkout@v1

      - name: Install Terraform
        run: |
          tf_version=$TERRAFORM_VERSION
          wget -q  https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip 
          unzip -qq terraform_"$tf_version"_linux_amd64.zip  -y
          sudo mv terraform /usr/local/bin/
        

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        run: |
          cd infra
          terraform init -input=false

      - name: Terraform validation
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
